service: "Artisan-application-python-http-api"
frameworkVersion: '3'
provider:
  name: aws
  runtime: python3.11
  region: ${self:custom.${self:provider.stage}.region}
  stage: ${opt:stage, self:custom.defaultEnv}
  timeout: 15
  memorySize: 128
  environment:
    COGNITO_USER_POOL_ID: eu-west-2_aAiz68RUa
    COGNITO_CLIENT_ID: fsevtbl0am0q2gr5enlg0pbno
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - ssm:GetParameters
          Resource: "arn:aws:ssm:eu-west-2:628479575487:parameter/DB_*"
        - Effect: Allow
          Action:
            - cognito-idp:AdminCreateUser
            - cognito-idp:AdminSetUserPassword
            - cognito-idp:AdminGetUser
            - cognito-idp:AdminAddUserToGroup
            - cognito-idp:AdminInitiateAuth
          Resource: "arn:aws:cognito-idp:eu-west-2:628479575487:userpool/eu-west-2_aAiz68RUa"

functions:
  user_login:
    handler: handler.user_login
    events:
      - httpApi:
          path: /user_login
          method: post

  registerArtisan:
    handler: handler.registerArtisan
    events:
      - httpApi:
          path: /registerArtisan
          method: post

  getArtiAvail:
    handler: handler.getArtiAvail
    events:
      - httpApi:
          path: /getArtiAvail
          method: get



  registerCustomer:
    handler: handler.registerCustomer
    events:
      - httpApi:
          path: /registerCustomer
          method: post

  registerAdmin:
    handler: handler.registerAdmin
    events:
      - httpApi:
          path: /registerAdmin
          method: post

  createJobRequest:
    handler: handler.createJobRequest
    events:
      - httpApi:
          path: /createJobRequest
          method: post

  updateJobRequestStatus:
    handler: handler.updateJobRequestStatus
    events:
      - httpApi:
          path: /updateJobRequestStatus
          method: post

  createBooking:
    handler: handler.createBooking
    events:
      - httpApi:
          path: /createBooking
          method: post

  getCustomerBookings:
    handler: handler.getCustomerBookings
    events:
      - httpApi:
          path: /getCustomerBookings
          method: get

  createReview:
    handler: handler.createReview
    events:
      - httpApi:
          path: /createReview
          method: post

  searchNearbyArtisans:
    handler: handler.searchNearbyArtisans
    events:
      - httpApi:
          path: /searchNearbyArtisans
          method: get

  sendOtp:
    handler: handler.sendOtp
    events:
      - httpApi:
          path: /sendOtp
          method: post

  verifyOtp:
    handler: handler.verifyOtp
    events:
      - httpApi:
          path: /verifyOtp
          method: post

plugins:
  - serverless-python-requirements

custom:
  defaultEnv: qa
  hub:
    region: eu-west-2
  dev:
    region: eu-west-2
    profile: dev
  qa:
    region: eu-west-2
    profile: qa
  prod:
    region: eu-west-2
    profile: prod
  pythonRequirements:
    dockerizePip: non-linux